version: '3'
services:
  blogweb:
    image: fvthree/blogweb:v1
    ports:
      - "80:80"
    depends_on:
      - blogdb
      - blogapi
    networks:
      - backend
      - frontend

  blogapi:
    image: fvthree/blogapp:V1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - blogdb
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://blogdb:3306/blogpost?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql-user
      SPRING_DATASOURCE_PASSWORD: dummypassword  
    networks:
      - backend
      - frontend
      
  blogdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: blogpost
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: dummypassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - blogdbdata:/var/lib/mysql
    networks:
      - backend
    
volumes:
  blogdbdata: {}

networks:
  backend:
  frontend: